# cloudbuild.yaml — Build Docker depuis service/, push vers AR, déploiement sur GKE
timeout: "3600s"

substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "toxicity"
  _IMAGE_NAME: "toxicity-api"
  _CLUSTER: "toxicity-cluster"
  _ZONE: "europe-west1-b"
  _NAMESPACE: "toxicity"
  _DEPLOYMENT: "toxicity-api"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

steps:
  # 0) (facultatif) Affiche les versions
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["version"]

  # 1) Build image (context = service/) + cache AR
  - name: "gcr.io/cloud-builders/docker"
    dir: "service"
    args:
      [
        "build",
        "--tag","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
        "--cache-from","type=registry,ref=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest",
        "--cache-to","type=inline",
        "."
      ]

  # 2) Tag latest (pratique pour tests manuels)
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
      "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest"
    ]

  # 3) Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest"]

  # 4) Auth GKE
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container","clusters","get-credentials","${_CLUSTER}",
        "--zone","${_ZONE}","--project","$PROJECT_ID"
      ]

  # 5) Apply manifests (créent Service/Deployment/HPA si besoin)
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"
    args: ["apply","-n","${_NAMESPACE}","-f","k8s/"]

  # 6) Patch l’image du Deployment à chaque build
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"
    args:
      [
        "set","image","deployment/${_DEPLOYMENT}",
        "${_DEPLOYMENT}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
        "-n","${_NAMESPACE}"
      ]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest"
