timeout: "3600s"

substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "toxicity"
  _IMAGE_NAME: "toxicity-api"
  _CLUSTER: "toxicity-cluster"
  _ZONE: "europe-west1-b"
  _NAMESPACE: "toxicity"
  _DEPLOYMENT: "toxicity-api"

options:
  logging: CLOUD_LOGGING_ONLY
  # Pas de machineType → valeur par défaut autorisée

steps:
  # 0) (optionnel) versions
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["version"]

  # 1) Build image (contexte = service/)
  - name: "gcr.io/cloud-builders/docker"
    dir: "service"
    args:
      [
        "build",
        "-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
        "."
      ]

  # 2) Tag latest (utile pour tests manuels)
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
      "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest"
    ]

  # 3) Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest"]

  # 4) Auth GKE
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container","clusters","get-credentials","${_CLUSTER}",
        "--zone","${_ZONE}","--project","$PROJECT_ID"
      ]

  # 5) Apply manifests
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"
    args: ["apply","-n","${_NAMESPACE}","-f","k8s/"]

  # 6) Mettre à jour l’image du Deployment
  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"
    args:
      [
        "set","image","deployment/${_DEPLOYMENT}",
        "${_DEPLOYMENT}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
        "-n","${_NAMESPACE}"
      ]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest"
